
class Billplz():
    """
    Billplz Client

    Base class for interfacing Billplz API with convenience methods
    """

    def init_client(self, api_key, collection_id, test=False):
        """
        Initialize an instance of the Billplz Client

        :param api_key: Authorized API secret key to your billplz account
        :param collection_id: Collection ID that will contain the bills generated by this client
        :param test: Default False - Sets the base_url to live endpoint. True sets base_url to sandbox endpoint.

        Returns initialized instance of the Billplz Client
        """
        self.api_key = api_key
        self.collection_id = collection_id
        if test:
            self.base_url = self.__get_sandbox_endpoint()
        else:
            self.base_url = self.__get_live_endpoint()

        return self

    def __get_sandbox_endpoint(self):
        return "https://www.billplz-sandbox.com/api/"

    def __get_live_endpoint(self):
        return "https://www.billplz.com/api/"
